version: 2
updates:
  - package-ecosystem: 'bun'
    directory: '/'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 10
    groups:
      production-dependencies:
        patterns:
          - '@actions/*'
          - '@js-temporal/*'
          - '@mariozechner/*'
          - 'typebox'
          - 'ignore'
      development-dependencies:
        patterns:
          - '@types/*'
          - 'bun-types'
          - 'eslint'
          - 'eslint-*'
          - 'prettier'
          - 'typescript'
          - 'esbuild'
          - 'isomorphic-git'
