/**
 * Centralized prompt library for the PI coding agent action.
 * All textual prompts and messages should be defined here.
 */

export const SYSTEM_PROMPT =
  'You are a non-interactive assistant running in GitHub Actions CI/CD environment. You are usually tasked with code reviews and generating code changes. You will not interact with the user directly. The output (or error) you generate will be sent back as comment to the user';

/**
 * Prompts for the create_pull_request tool
 */
export const PULL_REQUEST_TOOL = {
  name: 'create_pull_request',
  label: 'Create Pull Request',
  description:
    'Create a new pull request on GitHub. This tool handles everything: automatically determines the default base branch, creates a new branch, pushes changes, and creates the PR. The branch name is auto-generated following the pi/issue{number}-{timestamp} pattern.',

  promptSnippet:
    'Create a pull request with title and description. The tool will automatically determine the default base branch, create a new branch, push changes, and create the PR.',

  guidelines: [
    'Always use the create_pull_request tool to create pull requests - do not use git commands or gh CLI directly.',
    'Make sure your changes are made (modified files exist) before calling this tool. The tool will detect changes, create branch, and create PR automatically. Do NOT use unless you have already applied changes and/or added new files.',
    'The tool will automatically generate a branch name in the format: pi/issue{number}-{timestamp}.',
    'Do NOT provide the "base" parameter unless the user explicitly requests a different target branch than the repository default. The tool will automatically detect the correct default branch.',
    'Use dryRun=true first to verify the PR configuration, then dryRun=false to create it.',
  ] as string[],

  parameters: {
    title: {
      description: 'Pull request title (should be descriptive and follow conventional commit format)',
    },
    body: {
      description:
        'Detailed description of changes in markdown format. If not provided, will auto-generate from issue context (e.g., "Fixes #27")',
    },
    base: {
      description:
        'EXPERT: Override the default target branch. Only use this if the user explicitly requests a different branch than the repository default. Do NOT guess or assume a branch name - leave this empty unless specifically instructed.',
    },
    dryRun: {
      description:
        'Set to true to simulate PR creation without actually creating it (for testing). Set to false to create the actual PR.',
    },
  },
} as const;

/**
 * PR body templates for auto-generated pull requests
 */
export const PR_BODY = {
  fromIssue: (issueNumber: number) =>
    `Fixes #${issueNumber}\n\nCreated by pi coding agent.`,
  fromPullRequest: (issueNumber: number) =>
    `Related to #${issueNumber}\n\nCreated by pi coding agent.`,
} as const;

/**
 * Error messages for pull request operations
 */
export const PR_ERRORS = {
  noChangesDetected:
    'No changes detected. Please add new files and/or make your changes before creating a pull request.',
  creationFailed: (message: string) =>
    `[create_pull_request] Failed to create pull request: ${message}`,
} as const;

/**
 * Success messages for pull request operations
 */
export const PR_SUCCESS = {
  pullRequestCreated: (prNumber: number, prUrl: string) =>
    `Pull request #${prNumber} created: ${prUrl}`,
  dryRunPrefix: '[DRY RUN]',
  dryRunMessage: (title: string, bodyText: string, baseBranch: string, head: string) =>
    `[DRY RUN] Would create pull request:\n- Title: ${title}\n- Body: ${bodyText || '(empty)'}\n- Base: ${baseBranch}\n- Head: ${head}`,
} as const;

/**
 * Tool execution messages
 */
export const TOOL_EXECUTION = {
  createPullRequest: {
    cancelled: 'Pull request creation was cancelled',
    called: '\n=== create_pull_request tool called ===',
  },
} as const;

/**
 * Tool registration messages
 */
export const TOOL_REGISTRATION = {
  createPullRequest: '[create_pull_request] Tool registered successfully',
} as const;

/**
 * Debug messages for pull request operations
 */
export const PR_DEBUG = {
  title: (title: string) => `Title: ${title}`,
  autoGeneratedBranch: (head: string) => `Auto-generated branch: ${head}`,
  base: (base: string) => `Base: ${base}`,
  dryRun: (dryRun: boolean) => `DryRun: ${dryRun}`,
  usingProvidedBase: (baseBranch: string) => `Using provided base branch: ${baseBranch}`,
  usingDefaultFromContext: (baseBranch: string) => `Using default branch from context: ${baseBranch}`,
  fetchingDefaultBranch: 'Fetching repository default branch from GitHub API...',
  fetchedDefaultBranch: (baseBranch: string) => `Fetched default branch: ${baseBranch}`,
  autoGeneratedBody: (issueNumber: number) => `Auto-generated body from issue #${issueNumber}`,
  preparingBranchAndChanges: 'Preparing branch and changes via GitHub API...',
  gettingBaseRef: (baseBranch: string) => `Getting base branch "${baseBranch}" reference...`,
  baseBranchSha: (sha: string) => `Base branch SHA: ${sha}`,
  gettingBaseTree: 'Getting base branch tree...',
  foundFilesInBase: (count: number) => `Found ${count} files in base branch`,
  scanningLocalFiles: 'Scanning local files for changes...',
  ignoredFile: (relativePath: string) => `Ignored: ${relativePath}`,
  newFile: (relativePath: string) => `New file: ${relativePath}`,
  modifiedFile: (relativePath: string) => `Modified file: ${relativePath}`,
  skippingLargeFile: (relativePath: string) => `Skipping large file (>1MB): ${relativePath}`,
  skippingBinaryFile: (relativePath: string) => `Skipping file (likely binary): ${relativePath}`,
  foundChangedFiles: (count: number) => `Found ${count} changed file(s)`,
  creatingBranch: (head: string) => `Creating new branch "${head}"...`,
  branchCreatedSuccessfully: 'Branch created successfully',
  creatingBlobs: 'Creating blobs for changed files...',
  createdBlob: (path: string, sha: string) => `Created blob for ${path}: ${sha}`,
  createdBlobs: (count: number) => `Created ${count} blob(s)`,
  creatingTree: 'Creating tree with changes...',
  createdTree: (sha: string) => `Created tree: ${sha}`,
  creatingCommit: 'Creating commit...',
  createdCommit: (sha: string) => `Created commit: ${sha}`,
  updatingBranchRef: 'Updating branch reference...',
  branchUpdatedSuccessfully: 'Branch updated successfully',
  creatingPullRequest: 'Creating pull request...',
} as const;
